In [1]:
import numpy as np

## Questão 1 - Crie um numpy array com 10 elementos 0, exceto o elemento de índice 6, que deve ser 20

In [3]:
my_array = np.zeros(10)
my_array[6] = 20
my_array

array([ 0.,  0.,  0.,  0.,  0.,  0., 20.,  0.,  0.,  0.])

## Questão 2 - Crie uma função que receba um numpy array e retorne um array de 20 elementos contendo apenas o maior elemento do array recebido

In [10]:
def func1(array):
    max_ = array.max()
    return np.full(20, max_)

In [11]:
func1(np.array([4,5,7,89,11]))

array([89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
       89, 89, 89])

## Questão 3 - Faça uma função que receba um vetor, eleve ele ao quadrado, some 3, pegue apenas o elementos que são diferentes de 4 e, por último, divida por 4. Depois, retorne esse vetor modificado

In [13]:
def func2(array):
    array = (array ** 2) + 3
    array = array[array != 4]
    array = array / 4
    return array

In [16]:
func2(np.array([1,2,3,4,5,6]))

array([1.75, 3.  , 4.75, 7.  , 9.75])

## Questão 4 - Faça uma função que receba dois array, junte os dois e retorne

In [19]:
def func3(array1, array2):
    return np.concatenate((array1, array2))

In [18]:
func3(np.array([1,2,3,4,5,6]), np.array([6,5,4,3,2,1]))

array([1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1])

## Questão 5 - Faça uma função que descreva meu array exibindo os seguintes dados com até 3 casas decimais: máx, min, média, desvio padrão (standard deviation). A exibição deve ser da seguinte forma:

```
******************************
Array: array([0, 5, 6, 8, 9])

Max: 9
Min: 0
Media: 5.6
Desvio padrao: 3.137
******************************
```

In [27]:
def func4(array):
    print('*' * 35)
    print(array)
    print(f'\nMax: {np.round(array.max(), 3)}\nMin: {np.round(array.min(), 3)}\nMedia: {np.round(array.mean(), 3)}\nDesvio padrao: {np.round(array.std(), 3)}')
    print('*' * 35)

In [28]:
func4(np.array([0, 5, 6, 8, 9]))

***********************************
[0 5 6 8 9]

Max: 9
Min: 0
Media: 5.6
Desvio padrao: 3.137
***********************************
