In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import joblib



In [52]:
URL = "https://raw.githubusercontent.com/ricardo-jr37/mlflow_tutorial/master/data/wine.data"

df = pd.read_csv(URL)

cols = ["label"]

cols.extend(["feature_" + str(i) for i in range(1,14)])

df.columns = cols

df

label  feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0        1      13.20       1.78       2.14       11.2        100       2.65   
1        1      13.16       2.36       2.67       18.6        101       2.80   
2        1      14.37       1.95       2.50       16.8        113       3.85   
3        1      13.24       2.59       2.87       21.0        118       2.80   
4        1      14.20       1.76       2.45       15.2        112       3.27   
..     ...        ...        ...        ...        ...        ...        ...   
172      3      13.71       5.65       2.45       20.5         95       1.68   
173      3      13.40       3.91       2.48       23.0        102       1.80   
174      3      13.27       4.28       2.26       20.0        120       1.59   
175      3      13.17       2.59       2.37       20.0        120       1.65   
176      3      14.13       4.10       2.74       24.5         96       2.05   

     feature_7  feature_8  feature_9  feature_10  feature_11  feature_12  \
0         2.76       0.26       1.28        4.38        1.05        3.40   
1         3.24       0.30       2.81        5.68        1.03        3.17   
2         3.49       0.24       2.18        7.80        0.86        3.45   
3         2.69       0.39       1.82        4.32        1.04        2.93   
4         3.39       0.34       1.97        6.75        1.05        2.85   
..         ...        ...        ...         ...         ...         ...   
172       0.61       0.52       1.06        7.70        0.64        1.74   
173       0.75       0.43       1.41        7.30        0.70        1.56   
174       0.69       0.43       1.35       10.20        0.59        1.56   
175       0.68       0.53       1.46        9.30        0.60        1.62   
176       0.76       0.56       1.35        9.20        0.61        1.60   

     feature_13  
0          1050  
1          1185  
2          1480  
3           735  
4          1450  
..          ...  
172         740  
173         750  
174         835  
175         840  
176         560  

[177 rows x 14 columns]

In [53]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, 1:]

y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25)

In [54]:
from pyexpat import model


k = 7
knn = KNeighborsClassifier(n_neighbors=k)

model = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", knn)])

model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=7))])

In [55]:
y_pred = model.predict(X_test)

In [56]:
def get_metrics(y_test:list, y_pred:list):
    ac = accuracy_score(y_test, y_pred)
    pr = precision_score(y_test, y_pred, average= "weighted")
    rc = recall_score(y_test, y_pred, average= "weighted")
    f1 = f1_score(y_test, y_pred, average= "weighted")
    
    return(ac, pr, rc, f1)


mc = confusion_matrix(y_test.values.ravel(), y_pred)
ac, pr, rc, f1 = get_metrics(y_test, y_pred)

print(f" acuracy:   {ac}\n precision: {pr}\n recall:    {rc}\n f1 score:  {f1}\n\n  Matrix de confusão: \n{mc}")

 acuracy:   0.9444444444444444
 precision: 0.9439458689458688
 recall:    0.9444444444444444
 f1 score:  0.9436530547641658

  Matrix de confusão: 
[[20  1  0]
 [ 1 12  1]
 [ 0  0 19]]


In [57]:
file_name = "knn_model_v1.pkl"

In [58]:
joblib.dump(model, file_name)

['knn_model_v1.pkl']

In [59]:
val_model = joblib.load("knn_model_v1.pkl")

val_model.predict(X_val)

array([2, 2, 2, 2, 1, 3, 3, 2, 2, 2, 3, 3, 1, 3, 2, 1, 2, 1, 2, 1, 2, 3,
       2, 1, 2, 2, 1, 1, 2, 2, 2])

In [60]:
val_model.score(X_val, y_val)

0.8387096774193549

In [2]:
idade = [3, 5, 6, 8, 9, 9, 9]

In [5]:
import numpy as np

In [7]:
df = np.std(idade)

In [8]:
df

2.2038926600773587

In [2]:
a = "willian"

In [ ]:
b = 