# Matrizes com Numpy

Antes de iniciarmos com o Numpy, vamos rever o que é um array n-dimensional no Numpy:

![imgs/img1.png](imgs/img1.jpg)

In [ ]:
[[[1, 2], [4, 3], [7, 4]], [[2, X], [9, Y], [7, 5]]]

In [ ]:
[[[1,4,7], [2,9,7], ...], [[2,3,4], [], ...]]

***********************

![imgs/img2.png](imgs/img2.jpg)

#### Exibindo arrays

Quando você exibe um array, o Numpy monta a visualização da seguinte forma:

- o último eixo (axis) é "printado" da esquerda para a direita
- o penúltimo é exibido de cima para baixo
- o outros são exibidos de cima para baixo com uma linha vazia entre eles

In [3]:
np.array([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [4]:
import numpy as np

## Usando números aleatórios no Numpy

### Rand

Gera números aleatórios de uma distribuição uniforme entre 0 e 1. Passamos o shape como argumento

In [11]:
np.random.rand(2,3,3)

array([[[0.02087627, 0.3190045 , 0.78722113],
        [0.79018864, 0.45205221, 0.18938603],
        [0.52575509, 0.41429411, 0.92478396]],

       [[0.35353679, 0.82552861, 0.20996959],
        [0.37608903, 0.3899484 , 0.65204528],
        [0.92016681, 0.46103397, 0.17129216]]])

### Randn

Gera números advindos de uma distribuição normal padrão. Passamos o shape como argumento.


In [13]:
np.random.randn(10, 10)

array([[ 1.16635516,  0.1461136 , -0.22090021, -0.46225469, -0.01049572,
         0.60056355,  1.30637167,  0.48383826,  1.36328101,  1.81554617],
       [ 0.64806481,  0.23012094,  0.63877333,  1.69846347, -0.21019368,
        -1.27856065,  0.11355789, -0.47275256,  0.49084447,  0.32139555],
       [ 0.61152173,  0.33903681,  0.37305698, -0.65745062, -0.53566081,
         0.9357091 ,  0.68314253,  0.74395283, -0.97546162, -0.65940909],
       [ 1.59672254, -1.29824895, -1.9034091 , -1.23592678,  1.547065  ,
         1.3568301 , -0.58282727,  1.23446189,  0.98552324,  0.59339437],
       [ 0.10393846, -1.34222478, -0.15678524, -1.831991  ,  0.72474179,
         0.20210712, -1.20338282,  0.91049827,  0.77996779,  1.2012257 ],
       [-2.27443329,  0.00578399, -0.46482729,  1.84088741, -1.0628452 ,
        -0.24164061, -0.13009686,  1.96837331,  1.29107468, -1.32013165],
       [-0.40596379, -0.72978891,  0.51223841,  0.69473173, -0.57378812,
         0.05821336, -1.21469023,  0.60351385

### Randint

Permite que voce passe um intervalo, o qual será utilizado para gerar número inteiros com base em uma distribição uniforme. Passamos os limites e o shape como parâmetros.

- low -> inclusivo
- high -> exclusivo

In [23]:
np.random.randint(0, 11, (4,4))

array([[ 5, 10,  3,  9],
       [ 3,  6,  6,  1],
       [ 6,  4,  2,  7],
       [ 5, 10,  0,  4]])

## Copiando ndarrays

Muito cuidado na hora de copiar arrays, atribuindo eles a outras variáveis, pois a passagem referência.

In [29]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [25]:
b = a
b

array([1, 2, 3, 4, 5])

In [26]:
b[-1] = 10
b

array([ 1,  2,  3,  4, 10])

In [27]:
a

array([ 1,  2,  3,  4, 10])

In [30]:
b = a.copy()
b

array([1, 2, 3, 4, 5])

In [31]:
b[-1] = 10
b

array([ 1,  2,  3,  4, 10])

In [32]:
a

array([1, 2, 3, 4, 5])

## Indexing e slicing em matrizes

In [34]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
matriz[0][1]

2

In [41]:
matriz[:, 1]

array([2, 5, 8])

In [43]:
matriz[:, -2:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
matriz[:, [0, 1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
matriz[:, [0,-1]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [56]:
np.diagonal(matriz)

array([1, 5, 9])

## Operações básicas aplicadas nos eixos de uma matriz

Lembram as funcoes da ultima aula, como np.zeros e np.ones? Podemos passar o shape que quisermos como argumento!


In [57]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
matriz.sum(axis=0)

array([ 6, 15, 24])

In [64]:
matriz.max(axis=1)

array([3, 6, 9])

In [66]:
a = np.random.randint(10, size=(3,3,3))
a

array([[[8, 8, 9],
        [2, 7, 0],
        [9, 9, 8]],

       [[8, 6, 1],
        [1, 9, 6],
        [9, 9, 1]],

       [[9, 0, 1],
        [7, 7, 9],
        [5, 7, 6]]])

In [73]:
a.sum(axis = 2)

array([[25,  9, 26],
       [15, 16, 19],
       [10, 23, 18]])

## Mudando o formato de uma matriz: reshape, concatenate, vstack e hstack

### reshape

In [83]:
array = np.array([1,2,3,4,5,6,7,8,9, 10, 11, 12])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
array.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
matriz.shape

(3, 3)

In [88]:
matriz.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
matriz.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### concatenate

É a operação "mãe" das outras. Com ela, podemos fazer o mesmo que fazemos com vstack e hstack.

In [99]:
array1 = np.array([[1,2,3]])
array2 = np.array([[4,5,6,4]])

In [100]:
array1.shape, array2.shape

((1, 3), (1, 4))

In [102]:
np.concatenate([array1, array2], axis=1)

array([[1, 2, 3, 4, 5, 6, 4]])

### vstack

Empilhamento vertical

In [105]:
array1 = np.array([[1,2,3]])
array2 = np.array([[4,5,6]])
array3 = np.array([[7,8,9]])

In [107]:
np.vstack((array1, array2, array3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### hstack

Empilhamento horizontal

In [108]:
array1 = np.array([[1,2,3]])
array2 = np.array([[4,5,6]])
array3 = np.array([[7,8,9]])

In [109]:
np.hstack((array1, array2, array3))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Operações matriciais

O numpy permite que façamos uma série de operações muito utilizadas em álgebra linear como:

- Transpor uma matriz (Mudar linhas para colunas e colunas para linhas);
- Realizar multiplicação matricial
- Criar matrizes identidades

E muitas outras, como podemos ver em: https://numpy.org/doc/stable/reference/routines.linalg.html

### Matriz identidade

É uma matriz onde todos os elementos são zeros exceto a diagonal, que é preenchida por 1's.

In [111]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [112]:
np.eye(9, 7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Multiplicação de matriz

![image.png](imgs/img3.jpg)

In [116]:
matriz1 = np.array([[-1,3], [4,2]])
matriz2 = np.array([[1,2], [3,4]])

In [119]:
## matriz1 * matriz2 --> JEITO ERRADO

np.matmul(matriz1, matriz2)

array([[ 8, 10],
       [10, 16]])

In [120]:
matriz1 @ matriz2

array([[ 8, 10],
       [10, 16]])

### Transpondo matrizes

![image.png](imgs/img4.jpg)

In [121]:
matriz = np.array([[1,2], [3,4], [5,6]])
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
matriz.transpose(1, 0)

array([[1, 3, 5],
       [2, 4, 6]])

In [129]:
a = np.random.randint(10, size=(4,3,2)) ## 0 -> 2, 1 -> 4, 2 -> 3
a

array([[[1, 5],
        [8, 4],
        [4, 6]],

       [[2, 8],
        [6, 4],
        [5, 7]],

       [[7, 7],
        [4, 0],
        [5, 4]],

       [[7, 8],
        [8, 8],
        [0, 1]]])

In [131]:
a.shape ## (2, 4, 3)

(4, 3, 2)

In [132]:
ANTIGA = (4, 3, 2) # 0 = 4, 1 = 3, 2 = 2
NOVA = (3, 4, 2) 

In [ ]:
0, 1, 2 -> 2, 0, 1 -> 1, 2, 0

In [136]:
a.transpose(1, 0, 2)

array([[[1, 5],
        [2, 8],
        [7, 7],
        [7, 8]],

       [[8, 4],
        [6, 4],
        [4, 0],
        [8, 8]],

       [[4, 6],
        [5, 7],
        [5, 4],
        [0, 1]]])

## Extra: Calculando moda com o numpy

Abaixo, veremos um jeito de calcular a moda utilizando o Numpy. Porém, também é possível fazer usando outra biblioteca, baseada em Numpy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html

In [137]:
a = np.array([1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5])

In [138]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [139]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4, 5]), array([8, 9, 7, 6, 5], dtype=int64))

In [140]:
np.array([1, 2, 3, 4, 5])[1]

2

In [141]:
np.array([8, 9, 7, 6, 5]).argmax()

1

In [142]:
unique_array, counts = np.unique(a, return_counts=True)
unique_array[counts.argmax()]

2