# Matrizes com Numpy

Antes de iniciarmos com o Numpy, vamos rever o que é um array n-dimensional no Numpy:

![imgs/img1.png](imgs/img1.jpg)

***********************

![imgs/img2.png](imgs/img2.jpg)

#### Exibindo arrays

Quando você exibe um array, o Numpy monta a visualização da seguinte forma:

- o último eixo (axis) é "printado" da esquerda para a direita
- o penúltimo é exibido de cima para baixo
- o outros são exibidos de cima para baixo com uma linha vazia entre eles

In [1]:
import numpy as np

## Usando números aleatórios no Numpy

### Rand

Gera números aleatórios de uma distribuição uniforme entre 0 e 1. Passamos o shape como argumento

In [5]:
np.random.rand(3)

array([0.71463166, 0.37895747, 0.0039669 ])

In [6]:
np.random.rand(3,3)

array([[0.39830836, 0.86466911, 0.48305147],
       [0.381302  , 0.01824722, 0.57605506],
       [0.02970811, 0.47559738, 0.47865571]])

### Randn

Gera números advindos de uma distribuição normal padrão. Passamos o shape como argumento.


In [9]:
np.random.randn(3)

array([-0.42128337, -0.17334936, -0.2330406 ])

In [8]:
np.random.randn(4, 4)

array([[-0.85837579, -1.42561016,  0.55852356,  0.30943713],
       [ 0.3388262 , -0.28524817,  0.35021453, -0.01713794],
       [ 0.2582992 , -0.72075744,  0.70078249, -0.58523434],
       [-0.38754993, -0.51827964,  1.16401818, -1.24378242]])

### Randint

Permite que voce passe um intervalo, o qual será utilizado para gerar número inteiros com base em uma distribição uniforme. Passamos os limites e o shape como parâmetros.

- low -> inclusivo
- high -> exclusivo

In [12]:
np.random.randint(low=0, high=20, size=(3,))

array([19, 16, 14])

In [11]:
np.random.randint(low=0, high=20, size=(3,2))

array([[ 9,  7],
       [ 6,  4],
       [13,  1]])

## Copiando ndarrays

Muito cuidado na hora de copiar arrays, atribuindo eles a outras variáveis, pois a passagem é por referência.

In [25]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
b = a
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
b[2, 2] = 10
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [28]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

Opa, queriamos mudar só a variável "b", mas mudamos "a" também. O que fazer?

In [29]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
b = a.copy()
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
b[2, 2] = 10
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing e slicing em matrizes

In [34]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# quero o primeiro elemento da primeira linha

# faziamos assim em listas, ne?
matriz[0][0]

1

In [36]:
matriz[0, 0]

1

In [37]:
# quero todos os elementos da primeira linha
matriz[0]

array([1, 2, 3])

In [38]:
matriz[0, :]

array([1, 2, 3])

In [39]:
# quero o segundo e o terceiro elemento da segunda linha
matriz[1, 1:]

array([5, 6])

In [40]:
matriz[1, [1,2]]

array([5, 6])

## Operações básicas aplicadas nos eixos de uma matriz

Lembram as funcoes da ultima aula, como np.zeros e np.ones? Podemos passar o shape que quisermos como argumento!


In [44]:
matriz = np.ones((3,2))
matriz

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Quero somar os elementos de cada linha. Será que vamos conseguir o resultado que queriamos?

In [45]:
matriz.sum()

6.0

Precisamos passar o eixo!

Esse eixo representa o eixo onde "agruparemos" para realizar a operação que queremos. Por exemplo, se queremos saber a soma de cada linha, precisamos somar cada elemento em cada coluna dessa linha. Logo, estamos "agrupando" as colunas e somando elas. Por isso, passamos axis=1.

In [50]:
# Perceba que o resultado tem apenas 3 elementos, ja que so temos tres linhas
matriz.sum(axis=1)

array([2., 2., 2.])

Quero somar os elementos em cada coluna:

In [49]:
# Perceba que o resultado tem apenas 2 elementos, ja que so temos duas colunas
matriz.sum(axis=0)

array([3., 3.])

O mesmo vale para outras funções vistas na aula anterior.

In [63]:
matriz.mean(axis=0)

array([1., 1.])

In [64]:
matriz.mean(axis=1)

array([1., 1., 1.])

## Mudando o formato de uma matriz: reshape, concatenate, vstack e hstack

### reshape

In [75]:
array = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
array

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [78]:
array.reshape(3, 4)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [80]:
# O -1 quer dizer: cria quantas linhas/colunas voce quiser, mas o outro eixo eu quero que tenha tamanho X.
array.reshape(-1, 4)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [81]:
matriz = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
matriz

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [83]:
matriz.reshape(4,3)

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 3],
       [3, 3, 3]])

In [84]:
matriz.reshape(-1)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

### concatenate

É a operação "mãe" das outras. Com ela, podemos fazer o mesmo que fazemos com vstack e hstack.

In [102]:
a = np.array([[1,1,1,1]])
b = np.array([[2,2,2,2]])
c = np.array([[3,3,3,3]])

In [105]:
np.concatenate((a,b,c), axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [106]:
np.concatenate((a,b,c), axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

### vstack

Empilhamento vertical

In [107]:
a = np.array([[1,1,1,1]])
b = np.array([[2,2,2,2]])
c = np.array([[3,3,3,3]])

In [109]:
np.vstack((a,b,c))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [ ]:
matriz_1 = np.array([[1,1,1], [2,2,2]])
matriz_2 = np.array([[3,3,3], [4,4,4]])

In [114]:
np.vstack((matriz_1, matriz_2))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

### hstack

Empilhamento horizontal

In [110]:
a = np.array([[1,1,1,1]])
b = np.array([[2,2,2,2]])
c = np.array([[3,3,3,3]])

In [111]:
np.hstack((a,b,c))

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [112]:
matriz_1 = np.array([[1,1,1], [2,2,2]])
matriz_2 = np.array([[3,3,3], [4,4,4]])

In [113]:
np.hstack((matriz_1,matriz_2))

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

## Operações matriciais

O numpy permite que façamos uma série de operações muito utilizadas em álgebra linear como:

- Transpor uma matriz (Mudar linhas para colunas e colunas para linhas);
- Realizar multiplicação matricial
- Criar matrizes identidades

E muitas outras, como podemos ver em: https://numpy.org/doc/stable/reference/routines.linalg.html

### Matriz identidade

É uma matriz onde todos os elementos são zeros exceto a diagonal, que é preenchida por 1's.

In [88]:
# So gera matrizes quadradas
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# Funciona quase igual o np.identity, mas permite gerar matrizes não quadradas
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

### Multiplicação de matriz

![image.png](imgs/img3.jpg)

In [92]:
A = np.array([[1,2], [3,4]])
B = np.array([[-1,3], [4,2]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[-1,  3],
        [ 4,  2]]))

Se usarmos o operador "\*", o que acontece?

In [94]:
B * A

array([[-1,  6],
       [12,  8]])

Ele fez a multiplicação elemento a elemento, mas queremos fazer uma multiplicação matricial como a vista acima, como fazer?

In [96]:
np.matmul(B, A)

array([[ 8, 10],
       [10, 16]])

In [97]:
B @ A

array([[ 8, 10],
       [10, 16]])

### Transpondo matrizes

![image.png](imgs/img4.jpg)

In [115]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
A.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [119]:
# Posso passar a ordem dos eixos que quero para a nova matriz
A.transpose(1, 0)

array([[1, 3, 5],
       [2, 4, 6]])

In [120]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

## Extra: Calculando moda com o numpy

Abaixo, veremos um jeito de calcular a moda utilizando o Numpy. Porém, também é possível fazer usando outra biblioteca, baseada em Numpy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html

In [60]:
a = np.array([1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5])

In [61]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4, 5]), array([8, 9, 7, 6, 5], dtype=int64))

In [62]:
unique_array, counts = np.unique(a, return_counts=True)
unique_array[counts.argmax()]

2